[project]
name = "kalman-mapper"
version = "0.1.0"
description = "An implementation of a Kalman Filter to the mapper algorithm"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.2",
]
